### ISSUE TITLE
📈 SSW Rules - Do you use strongly typed IDs?

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.CleanArchitecture#102]
Be good to add some performance metrics to this.  Apparently records have perf issues compared to classes.  Would be interesting to see if we can resolve this by using record structs.

https://youtu.be/dJxVj6390hk

**Comment by danielmackay** [comment]
@william-liebenberg - can you link to the rule or PR?

**Comment by william-liebenberg** [comment]
Link to the rule: https://www.ssw.com.au/rules/do-you-use-strongly-typed-ids/
