### ISSUE TITLE
🐛 Ensure Workflows work for forked repos

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.CleanArchitecture#154]
This issue was found by JK when trying to fix an issue via a fork: https://github.com/SSWConsulting/SSW.CleanArchitecture/pull/147 

We need to ensure that the workflows successfully run for any forked repos

**Comment by wicksipedia** [comment]
Done - see https://youtu.be/h05ZuwgOa8Q

Hey @jernejk 👋 feel free to contribute

**Comment by jernejk** [comment]
Is it possible now for external people to pass build. Last time, I didn't had enough permissions to pass the build.
