### ISSUE TITLE
👀 Review of Existing CA Rules

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.CleanArchitecture#164]
Review the existing set of Clean Architecture rules and compare it to the core principles of CA and our new CA workshop.

Find knowledge gaps and create tasks to create new rules to fill them.

**Comment by william-liebenberg** [comment]
## Rules to update:

1. Do you know how to improve the discoverability of your MediatR requests?
* https://www.ssw.com.au/rules/how-to-improve-the-discoverability-of-your-mediatr-requests/
* https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/184

2. Do you know the best approach to validate your client requests?
* https://www.ssw.com.au/rules/the-best-approach-to-validate-your-client-requests/
* https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/175

## Missing rules to add:

1. Minimal Endpoints
	* https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/173

2. Global Exceptions -> Problem Details
	* https://www.ssw.com.au/rules/do-you-return-detailed-error-messages/
	* no code examples
	* https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/174

3. Specifications Pattern
	* https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/176

4. Directory Build Props
	* https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/182

5. Respawn + TestContainers
	* https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/177

6. Architecture Tests
	* https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/178

7. Anemic vs Rich Domain Models
	* https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/179

8. Properly encapsulating Domain Models
	* https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/181

**Comment by danielmackay** [comment]
Closing as review has been done and new PBIs created
