### ISSUE TITLE
📈 SSW Rules - DDD - Do you know how to encapsulate Domain Models?

### ISSUE THREAD

**Issue by william-liebenberg** [SSWConsulting/SSW.CleanArchitecture#181]
A rich domain model should not allow other code to interact with the model in a way that would leave it in an invalid state.

This is usually done via encapsulation.  For example:

- private setters on properties
- functions (aka Behaviour) to update state
- ensuring required fields are passed in via constructors or factory methods
- encapsulate collections so that only allowed operations are exposed (e.g. allow adding an item to a collection, but don't allow removing or clearing)
- (more?)

**Comment by danielmackay** [comment]
Done
