### ISSUE TITLE
🧪 Add NSubstitute for Mocking

### ISSUE THREAD

**Issue by william-liebenberg** [SSWConsulting/SSW.CleanArchitecture#183]
Already referenced in the Unit Testing project, but no example tests are present.

Add a test that Mocks `IDateTime` to show how NSubstitute can be used.

**Comment by danielmackay** [comment]
We no longer have an `IDateTime` interface/service as we are now using the .NET 8 `TimeProvider` abstraction.

There are services or external infrstructure we could mock to show NSubstitute.

@william-liebenberg - are you happy to close this ticket?

**Comment by danielmackay** [comment]
@william-liebenberg - closing this ticket due to the above.  Let me know if this needs to be re-opened.
