### ISSUE TITLE
✨ OpenAPI/Swagger - Consider switching from NSwag to Swashbuckle

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.CleanArchitecture#202]
- We are not generating client side code anymore (which was one of the reasons we were using NSwag).
- Now that we are only generating the OpenAPI Spec, is it better to use NSwag or Swashbuckle to generate the spec
- We still want an API UI
- Check with @matt-goldman , @drwharris , Alex Rothwell on feedback/opinions around this
- Enum generation needs to also be considered as this is often a painpoint
- ~Consider using magic strings for endpoint routes~

~Notes~
~- Refit is another .NET library to assist with calling  REST APIs~

**Comment by drwharris** [comment]
I did a trial of this and its pretty straight forward. If you are generating a client then its a slightly different paradigm on usage, eg client.Users[identifier].GetAsyc() as opposed to client.GetUserAsync(Identifier). But in all it was pretty quick and easy to setup.
