### ISSUE TITLE
♻️ Exclude unwanted files from template

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.CleanArchitecture#210]
Cc: @danielmackay 

Hi 

### Pain

The template config doesn't currently exclude the right things. For example, the `templates` folder and code of conduct are output in a build using our template.

### What code could be improved?

`template.json` could be improved - we can update the `exclude` section to more appropriately reflect what we want included in the build.

Thanks!

**Comment by danielmackay** [comment]
Hi @matt-goldman,

I don't think this is fixed.  I've just tried the latest version of the template and still see these folders in the output:

![image](https://github.com/SSWConsulting/SSW.CleanArchitecture/assets/2636640/b4b77f61-3638-4bcb-9a46-c8b252ab905e)

Can you investigate?

**Comment by matt-goldman** [comment]
Hey @danielmackay working on this now. Just confirming I should remove the following:

* `templates/`
* `.log4brains.yml`
* `CONTRIBUTING.md`
* `Directory.Build.props`
* `package.ps1`
* `Security.md`

**Comment by danielmackay** [comment]
Keep log4brains and directory.props
