### ISSUE TITLE
🗣️ Discuss using Results<T1, T2, ...> over .ProducesGet, .ProducesPost etc

### ISSUE THREAD

**Issue by Hona** [SSWConsulting/SSW.CleanArchitecture#225]
Currently we can have code like this:

```cs
app.MapGet("/weatherforecast", Results<Ok<WeatherForecast[]>, NotFound<string>, ProblemHttpResult> () =>
 TypedResults.Ok(blah))
.ProducesProblem(StatusCodes.Status500InternalServerError)
```

or in the way of the template (after expanding some extension methods)

```cs
app.MapGet("/weatherforecast", () =>blah)
.Produces<T>(StatusCodes.Status200OK)
        .Produces(StatusCodes.Status404NotFound)
        .ProducesProblem(StatusCodes.Status500InternalServerError);
```

I think the current way is better, due to a global exception handler converting exceptions to notfound, problemdetails etc.

If we didn't have that as a global exception handler then I would prefer the Results<> type

---

here you can see some MS guys using the Results<> 
https://github.com/davidfowl/BlazorBlog/blob/main/MyBlog.Api/PostsApi.cs

**Comment by danielmackay** [comment]
@Hona - I like how you're exploring ways we can improve out template.

However, as per our conversation we've decided to keep this as-is, due to how we handle global exceptions.
