### ISSUE TITLE
♻️ Remove TodoItem from solution

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.CleanArchitecture#284]
Once #277 is merged, we need to remove TodoItems as it doesn't fit in with the domain model

- [ ] Check there are no references to 'Todo' in the code
- [ ] Clean slate the migrations to remove the 'Todo' tables

**Comment by danielmackay** [comment]
Should be done already

**Comment by danielmackay** [comment]
Fixed by https://github.com/SSWConsulting/SSW.CleanArchitecture/pull/379
