### ISSUE TITLE
✨ Consider Adding .NET Aspire

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.CleanArchitecture#362]
This could be used to:
- Spin up local DB
- Spin up API (existing)
- Spin up FE (new)
- Spin up Identity Server (new)

![Image](https://github.com/user-attachments/assets/3fe9d7b3-f7c2-4829-97d0-a46a5a1a5a4c)
https://www.youtube.com/watch?v=1yEZ8LqqwnE

- [x] Remove docker-compose
- [x] Remove up.ps1
- [x] Add service defaults

**Comment by Hona** [comment]
Nice idea, @danielmackay! 

As a consumer of open source, this would be nice to see.

Combined with `azd` and other tooling, you can get a nice local f5 experience, but also a nice cloud deploy strategy.
