### ISSUE TITLE
📝 CA Workshop Marketing PPT

### ISSUE THREAD

**Issue by william-liebenberg** [SSWConsulting/SSW.CleanArchitecture#72]
Split the original Clean Architecture PPT from the retreat into smaller PPT specific for Workshops

**Comment by danielmackay** [comment]
@william-liebenberg - is this the workshop marketing PPT (i.e. NOT the workshop content PPT)?

**Comment by william-liebenberg** [comment]
Correct :)

**Comment by danielmackay** [comment]
@william-liebenberg - I thought this had already been split?  What is still outstanding?

**Comment by william-liebenberg** [comment]
The PPT above IS the one that got split out from the original big kahuna PPT.

@matt-goldman and I should review the slides this week and make final changes.

**Comment by danielmackay** [comment]
@william-liebenberg - we'll also need to update the event agenda: https://www.ssw.com.au/ssw/Events/Training/Clean-Architecture-Workshop.aspx

Hopefully this information could be included in the marketing PPT so we can give to Camilla.

**Comment by danielmackay** [comment]
@william-liebenberg @matt-goldman - I've added the agenda as new slides.  Can you please review?

https://sswcom.sharepoint.com/:p:/s/CleanArchitecturev2/ERvFIRuzgs5BpORoeYKqn5gBQoGijXzS7sIk61XnvpEpZQ?e=3Aw5N5&nav=eyJzSWQiOjM2MywiY0lkIjoxMDM5ODUxODQ5fQ

**Comment by william-liebenberg** [comment]
@danielmackay - reviewed and left a couple of new comments

**Comment by danielmackay** [comment]
@matt-goldman - did you end up working on this last Friday?  What else is remaining here?

**Comment by matt-goldman** [comment]
All looks good to me know
